apiVersion: v1
kind: Service
metadata:
  name: pomerium-databroker
spec:
spec:
  selector:
    app.kubernetes.io/name: pomerium
  ports:
    - name: databroker
      port: 5443
      targetPort: databroker
