log_level: info
proxy_log_level: info
services: all

address: "0.0.0.0:443"
ssh_address: "0.0.0.0:22"

idp_provider: oidc
idp_provider_url: http://mock-idp.example.com:8024
idp_client_id: CLIENT_ID
idp_client_secret: CLIENT_SECRET

authenticate_service_url: https://authenticate.example.com:443

databroker_storage_type: memory

certificate_file: _wildcard.example.com.pem
certificate_key_file: _wildcard.example.com-key.pem

cookie_secret_file: /pomerium/demo_cookie_secret
shared_secret_file: /pomerium/demo_shared_secret

ssh_host_key_files:
  - /pomerium/demo_host_key
ssh_user_ca_key_file: /pomerium/demo_user_ca_key

runtime_flags:
  ssh_upstream_tunnel: true
