events {}

stream {
    log_format tcp '$remote_addr -> $upstream_addr [$status] '
                   'bytes_sent=$bytes_sent bytes_received=$bytes_received '
                   'session_time=$session_time';
    access_log /dev/stdout tcp;

    server {
        listen 443;
        proxy_pass pomerium:443;
        proxy_timeout 1h;
    }
}
