apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium-console
spec:
  template:
    spec:
      containers:
        - name: pomerium-console
<<<<<<< HEAD
          args: ['serve']
          args:
            - --tls-derive=pomerium-console.$(POMERIUM_ENTERPRISE_NAMESPACE).svc.cluster.local
            - serve
=======
          args: ["serve"]
>>>>>>> parent of 6e6f886 (runs prettier, adds keywords to front matter)
