apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium-console
spec:
  template:
    spec:
      containers:
        - name: pomerium-console
          args:
            - --tls-derive=pomerium-console.$(POMERIUM_ENTERPRISE_NAMESPACE).svc.cluster.local
            - serve
