import apiSidebar from './content/docs/api/sidebar';

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentation: [
    'docs/index',
    {
      type: 'category',
      label: 'Get Started',
      link: {type: 'doc', id: 'docs/get-started/quickstart'},
      items: [
        {
          type: 'doc',
          id: 'docs/get-started/quickstart',
        },
        {
          type: 'category',
          label: 'Fundamentals Step-by-Step',
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/get-started/fundamentals',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deploy',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs/deploy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capabilities',
      items: [
        // Core Capabilities
        'docs/capabilities/authentication',
        'docs/capabilities/authorization',
        'docs/capabilities/getting-users-identity',
        'docs/capabilities/bearer-token-access',
        'docs/capabilities/routing',
        'docs/capabilities/routes-portal',
        'docs/capabilities/custom-domains',
        {
          type: 'category',
          label: 'Model Context Protocol (MCP)',
          link: {type: 'doc', id: 'docs/capabilities/mcp'},
          items: [{type: 'autogenerated', dirName: 'docs/capabilities/mcp'}],
        },
        // secondary capabilities
        'docs/capabilities/audit-logs',
        'docs/capabilities/kubernetes-access',
        'docs/capabilities/native-ssh-access',
        'docs/capabilities/reverse-tunneling',
        {
          type: 'category',
          label: 'Non-HTTP Protocols',
          link: {type: 'doc', id: 'docs/deploy/clients/clients'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/capabilities/non-http',
            },
          ],
        },
        // Enterprise
        {
          type: 'category',
          label: 'Session Recording',
          className: 'enterprise',
          link: {type: 'doc', id: 'docs/capabilities/session-recording'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/capabilities/session-recording',
            },
          ],
        },
        'docs/capabilities/branding',
        'docs/capabilities/self-remediation',
        'docs/capabilities/original-request-context',
        'docs/capabilities/service-accounts',
        'docs/capabilities/impersonation',
      ],
    },

    {
      type: 'category',
      label: 'Internals',
      link: {type: 'doc', id: 'docs/internals/architecture'},
      items: [{type: 'autogenerated', dirName: 'docs/internals'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {type: 'doc', id: 'docs/integrations'},
      description: 'Integrate external data sources with Pomerium',
      items: [{type: 'autogenerated', dirName: 'docs/integrations'}],
    },
  ],
  reference: [
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'doc',
        id: 'docs/reference',
      },
      items: [{type: 'autogenerated', dirName: 'docs/reference'}],
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
      },
      items: apiSidebar.filter(
        (item) => item.label !== 'pomerium.config.ConfigService',
      ),
    },
  ],
  guides: [
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Pomerium Guides',
        description:
          'Step by step guides for common apps, services, platforms, and use-cases with Pomerium!',
        keywords: ['guides'],
        slug: 'docs/guides',
      },
      items: [{type: 'autogenerated', dirName: 'docs/guides'}],
    },
  ],
};

module.exports = sidebars;
