/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentation: [{type: 'autogenerated', dirName: 'docs'}],
  reference: [
    {
      type: "category",
      label: "Reference",
      link: {
        type: "doc",
        id: "docs/reference/readme"
      },
      items: [
        {type: 'autogenerated', dirName: 'docs/reference'}
      ]
    }

  ],
  guides: [{type: 'autogenerated', dirName: 'docs/guides'}],
  enterprise: [{type: 'autogenerated', dirName: 'docs/enterprise'}]
};

module.exports = sidebars;
