authenticate_service_url: https://authenticate.localhost.pomerium.io
autocert: true
autocert_use_staging: true
idp_provider: google
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME

cookie_secret: REPLACE_ME
jwt_claims_headers: email

policy:
  - from: https://wiki.localhost.pomerium.io
    to: http://tiddlywiki:8080
    policy:
      - allow:
          or:
            - email:
                is: reader@example.com
            - email:
                is: writer@example.com
