apiVersion: v1
kind: Service
metadata:
  name: pomerium-console
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pomerium-enterprise
  ports:
    - name: app
      port: 80
      targetPort: app
      protocol: TCP
    - name: grpc-api
      port: 5443
      targetPort: grpc-api
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
