apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pomerium-enterprise
resources:
  - ./namespace.yaml
  - ./deployment
  - ./service
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: pomerium-console
