apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../console
  - ../core
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--bootstrap-service-account=true'
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pomerium-console
      namespace: pomerium-enterprise
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POMERIUM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-token
              key: token
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--sync-api-ingress=pomerium-enterprise/pomerium-console'
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: '--sync-api-token=$(POMERIUM_API_TOKEN)'
    target:
      group: apps
      version: v1
      kind: Deployment
      name: pomerium
      namespace: pomerium
