apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: pomerium-console
  name: pomerium-enterprise
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pomerium-console
  name: pomerium-console
  namespace: pomerium-enterprise
spec:
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: app
    - name: grpc-api
      port: 5443
      protocol: TCP
      targetPort: grpc-api
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: pomerium-console
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pomerium-console
  name: pomerium-console
  namespace: pomerium-enterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pomerium-console
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pomerium-console
    spec:
      containers:
        - args:
            - serve
          env:
            - name: TMPDIR
              value: /tmp
            - name: XDG_CACHE_HOME
              value: /tmp
            - name: AUDIENCE
              valueFrom:
                configMapKeyRef:
                  key: audience
                  name: enterprise
            - name: ADMINISTRATORS
              valueFrom:
                configMapKeyRef:
                  key: administrators
                  name: enterprise
                  optional: true
            - name: DATABROKER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: databroker_service_url
                  name: enterprise
                  optional: false
            - name: AUTHENTICATE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: authenticate_service_url
                  name: enterprise
                  optional: false
            - name: PROMETHEUS_URL
              valueFrom:
                configMapKeyRef:
                  key: prometheus_url
                  name: enterprise
                  optional: true
            - name: SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  key: shared_secret
                  name: enterprise
                  optional: false
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: enterprise
                  optional: false
            - name: DATABASE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: database_encryption_key
                  name: enterprise
                  optional: false
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: license_key
                  name: enterprise
                  optional: false
          image: docker.cloudsmith.io/pomerium/enterprise/pomerium-console:v0.20.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: app
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
          name: pomerium-console
          ports:
            - containerPort: 8701
              name: app
              protocol: TCP
            - containerPort: 8702
              name: grpc-api
              protocol: TCP
            - containerPort: 9092
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: app
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: pomerium-enterprise-docker
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      volumes:
        - emptyDir: {}
          name: tmp
