authenticate_service_url: https://authenticate.localhost.pomerium.io

idp_provider: REPLACE_ME
idp_client_id: REPLACE_ME
idp_client_secret: REPLACE_ME

cookie_secret: j9jZgysWVxCs3uqbmw9a2LxWwz1ZPLKQZ8v20eoDT8Y=
signing_key: REPLACE_ME
shared_secret: mxGl062SqkrbQKvqG9R2jqHqxq1Oi1BNj2AAeZHNq7c=

databroker_storage_type: postgres
databroker_storage_connection_string: postgresql://postgres:postgres@postgres/<database>?sslmode=disable

routes:
  - from: https://verify.localhost.pomerium.io
    to: http://verify:8000
    policy:
      - allow:
          or:
            - email:
                is: user@example.com
  - from: https://console.localhost.pomerium.io
    to: http://pomerium_console:8701
    allowed_users:
      - user@example.com
    pass_identity_headers: true
